Popup v6 windows
CommunityToolkit/Maui pull request #1086
Opened 2023-03-10 21:01 UTC by VladislavAntonyuk

### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #371 

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

2023-05-24 19:58 UTC, bijington commented
Thanks for this @VladislavAntonyuk it is in my queue to review as part of all open Popup related issues.

2023-05-24 20:21 UTC, VladislavAntonyuk commented
@bijington it still needs some changes (mostly related to background color). However, the main issue with disappearing during resizing and minimizing the window is solved.

2023-07-26 22:53 UTC, brminnick requested changes
Thanks Vlad! This is looking really good!

But, I'm seeing some unexpected behavior when using an Anchor. In the sample app, the Popup appears far to the right of the anchor.
![ScreenFlow](https://github.com/CommunityToolkit/Maui/assets/13558917/192a9889-2e23-4dcc-9146-a8b6ab101a73)

2023-07-27 00:42 UTC, pictos commented on src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs
> +			}
```suggestion
backgroundProperty?.SetValue(content, color.ToPlatform());

```

2023-07-27 00:43 UTC, pictos commented on src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs
> +	/// <param name="mauiContext"></param>
a lot of methods don't have the inline docs filled in. Can you address that?

2023-07-27 17:28 UTC, brminnick approved these changes

2023-07-27 17:31 UTC, brminnick commented
Thanks Vlad!! I approve. 

I've added the https://github.com/CommunityToolkit/Maui/labels/do%20not%20merge to ensure we don't accidentally merge this PR before releasing `CommunityToolkit.Maui v5.4.0`. 

This PR will be included in our release of `CommunityToolkit.Maui v6.0.0`.

2023-08-03 18:44 UTC, bijington approved these changes
Yes @VladislavAntonyuk !

2023-08-09 18:04 UTC, merged