Migrate Validators from XCT to MAUI #41, #42, #40, #38, #37
CommunityToolkit/Maui pull request #142
Opened 2021-10-15 13:26 UTC by VladislavAntonyuk

## Fixes

#41, #42, #40, #39, #38, #37, #43

## Description

Migrate validators from XCT to MAUI

![image](https://user-images.githubusercontent.com/33021114/137494644-5a32857a-34e5-4d9b-9e8d-5fb8fff3cb8c.png)
![image](https://user-images.githubusercontent.com/33021114/137495972-e891bfa6-26b7-4071-bfa6-43836a0ee13b.png)

2021-10-16 20:09 UTC, VladislavAntonyuk commented
@brminnick merge conflict are resolved

2021-11-09 16:27 UTC, brminnick commented
Unblocking this now that .NET MAUI supports Unit Tests 🎉

2021-11-10 03:57 UTC, brminnick requested changes
Thanks Vlad! 

I added the missing EmailValidationBehavior_UnitTests.

But we still need a few things:
- RequiredString Sample
- TextValidationBehavior UnitTests
- TextValidationBehavior Sample
- ValidationBehavior Unit Tests
  - Include tests for all public Properties + Methods
  - I recommend creating `MockValidationBehavior`
    ```cs
    class MockValidationBehavior : ValidationBehavior
    ```

2021-11-10 03:57 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Behaviors/MultiValidationBehavior_Tests.cs
> +        multiBehavior.Children.Add(behavior);
Let's add at least 3 `ValidationBehavior`s to `multiBehavior` to validate the "multi" part

2021-11-10 03:58 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Behaviors/EmailValidationBehavior_Tests.cs
> +	}
I got the test data from here: https://codefool.tumblr.com/post/15288874550/list-of-valid-and-invalid-email-addresses

2021-11-16 09:16 UTC, brminnick commented
Hey @VladislavAntonyuk! Just a thought - if you split this PR into smaller PRs, we could get a few of the validators merged while we work on the features that still need updating.

2021-11-16 10:42 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/Behaviors/Validators/EmailValidationBehavior.shared.cs
> +public class EmailValidationBehavior : TextValidationBehavior
to support all test cases we have to use this regex: http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html (the link from the website you suggested https://codefool.tumblr.com/post/15288874550/list-of-valid-and-invalid-email-addresses).
I think the regex looks ugly and almost impossible to maintain.
I am voting to MailAddress.TryCreate. if somebody creates a bug for the email validator, we will solve it for the specific scenario (maybe using regex)

2021-11-16 11:37 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui.UnitTests/Behaviors/EmailValidationBehavior_Tests.cs
> +	}
the regex looks ugly for these scenarios: http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html
even more, not all of the specified scenarios are valid. I saw this email `email@example` and it worked like a charm.

2021-11-16 16:11 UTC, VladislavAntonyuk commented
> Hey @VladislavAntonyuk! Just a thought - if you split this PR into smaller PRs, we could get a few of the validators merged while we work on the features that still need updating.

You are right. I thought the first PR would be the exact copy of XCT.
This PR requires base ValidationBehavior tests, so we cannot merge it.
I have almost finished the implementation. The only ValidationBehaviour left. So I think you can review and if everything looks good merge it tomorrow.

2021-12-06 20:39 UTC, brminnick approved these changes

2021-12-06 20:50 UTC, merged