Expander CollectionView GridLayout 1557
CommunityToolkit/Maui pull request #1567
Opened 2023-11-26 19:06 UTC by VladislavAntonyuk

### Linked Issues ###
 

 - Fixes #1557

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

![image](https://github.com/CommunityToolkit/Maui/assets/33021114/2d8749f7-9e42-4850-a41e-491cde6b76f8)

2023-11-26 19:34 UTC, brminnick commented
It looks like this fix only targets Windows. I'm seeing similar broken behavior on iOS + MacCatalyst with a CollectionView inside Expander. 

Any chance you could take a look at the other platforms too?

2023-12-15 12:30 UTC, VladislavAntonyuk commented
@brminnick as discussed at the meeting, I suggest merging it as it is (despite having some visual issues).

2024-01-26 16:31 UTC, leoslima13 commented
@brminnick @VladislavAntonyuk Do you guys have any predictions on when this will be completed? We can see several people having exactly this expansion problem within the CollectionView, I think this would be a good time for that

2024-02-27 14:37 UTC, vhugogarcia commented
Thanks @VladislavAntonyuk for updating the expander under CollectionView and GridLayout. 

I just tested it on Android and it works as expected, however it does not work on macOS and iOS _(see screenshot below)_:
<table style="padding:10px">
  <tr>
    <td> Android
         <img src="https://github.com/CommunityToolkit/Maui/assets/1047398/830a1a61-d598-4fec-925c-b4c87a3301eb"  alt="1" width = 279px height = 496px ></td>
      
 <td> macOS
<img src="https://github.com/CommunityToolkit/Maui/assets/1047398/312232c1-2c04-4a43-a796-8a0c62eeca04" align="right" alt="2" width = 279px height = 496px></td>
   <td> iOS
<img src="https://github.com/CommunityToolkit/Maui/assets/1047398/bfda397f-d67c-4850-a7df-1d581bf2e326" alt="3" width = 288px height = 512px></td>
  </tr>
</table>

On macOS/iOS, then you expand an item from the CollectionView all others disappear and it does not grow as expected. The same issue occurs on the horizontal items.

I will see if I can help with the macOS/iOS issue :)

2024-03-18 16:01 UTC, hayer commented
@vhugogarcia has there been any progress made on this for iOS/macOS? I am currently stuck with it not working on iOS.

2025-02-04 15:52 UTC, ne0rrmatrix commented
Looking good. One issue I am looking at in windows is: 
![image](https://github.com/user-attachments/assets/efd3e09e-d5e2-4a73-aed9-c1a007448867)

As you can see the items at bottom are being cut off with no image being displayed. It is not scrollable at all and items expand maybe one inch or so.

2025-02-04 15:59 UTC, ne0rrmatrix commented
In android on bottom of page it expands as expected but fails to unexpand when clicked closed. It does remove image and text but the space is left open. 

https://github.com/user-attachments/assets/12e431ee-e0a6-4cca-9ac8-4af40cb0c1fb

2025-02-04 16:03 UTC, ne0rrmatrix requested changes
Once you have fixed the issue in windows and android with expander either failing to open properly(Windows) or failing to close properly(Android) I will be happy to approve this. It is looking very good and I can say I see no issues except the above.

2025-02-04 22:05 UTC, VladislavAntonyuk commented
thank you @ne0rrmatrix, I will take a look at Windows, because it looks broken. Android at least renders correctly and I don't want to change the default cell size maui behavior.

2025-02-04 23:54 UTC, ne0rrmatrix requested changes
Window and android are working as expected now. On IOS there is one issue still. 
<img width="1920" alt="Screenshot 2025-02-04 at 3 52 18 PM" src="https://github.com/user-attachments/assets/7a386c64-eade-43ec-a55f-726f3e1f7ad2" />

2025-02-05 00:17 UTC, VladislavAntonyuk commented
@ne0rrmatrix , that is not an issue, just scroll

2025-02-05 00:20 UTC, ne0rrmatrix commented
> @ne0rrmatrix , that is not an issue, just scroll. it is a part of listview
Yes I see that now. My bad. It looks good on my end and you have made all the requested changes.

2025-02-05 00:21 UTC, ne0rrmatrix approved these changes

2025-02-05 00:22 UTC, VladislavAntonyuk commented
thank you. I will update docs and merge PR in the morning

2025-02-05 20:43 UTC, merged