Update Touch Behavior Sample
CommunityToolkit/Maui pull request #1784
Opened 2024-04-01 12:24 UTC by Axemasta

### Description of Change ###

Update the `TouchBehavior` sample gallery to show the recommended method of setting of setting the binding context for the `TouchBehavior`.

I have included a new usage with the `CommandParameter` to help clearup some confusion we've been seeing for people consuming this `Behavior` upon release.

 ### Linked Issues ###
 N/A

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

Documentation TODO

 ### Additional information ###

I've run `dotnet format` and checked that in, some minor changes all in the `TouchBehavior` area.

2024-04-04 22:23 UTC, brminnick commented
@Axemasta Could you resolve the merge conflicts?

It looks like the work we did on https://github.com/CommunityToolkit/Maui/pull/1791 caused a couple conflicts on this PR.

2024-04-27 22:54 UTC, brminnick requested changes
Thanks @Axemasta! It looks like the `LongPress | Hover` section is broken in this update. 

Could you fix that? And then we'll merge it!

2024-04-28 22:07 UTC, Axemasta commented
@brminnick I've pushed a fix & rebased ontop of main 👍

2024-04-28 22:38 UTC, brminnick approved these changes

2024-04-28 22:38 UTC, brminnick commented
Wonderful! Thank you sir 🫡

2024-04-28 22:38 UTC, merged