The most significant changes to the `MauiMediaElement` involve modern…
CommunityToolkit/Maui pull request #1868
Opened 2024-05-09 03:18 UTC by ne0rrmatrix

## Bug fix ##

 ### Description of Change ###

The most significant changes to the `MauiMediaElement` involve modernizing the fullscreen controls by transitioning from using static SVG images to adopting `FontIcon` elements for better flexibility and visual consistency. This shift enhances the user interface and interaction model for entering and exiting fullscreen mode. The key changes include:

1. **Removal of fullscreen.svg Resource**: The static `fullscreen.svg` image resource was removed, indicating a move away from static images for the fullscreen button.
2. **Introduction of Font Icons for Fullscreen Controls**: Replacing the `Image` with `FontIcon` elements for fullscreen controls, utilizing glyphs from the "Segoe MDL2 Assets" font for a more flexible and accessible approach.
3. **Adjustments to Fullscreen Button Logic**: The logic for toggling between the fullscreen and exit fullscreen buttons was refined, including the dynamic addition and removal of buttons and event handlers based on the fullscreen state.
4. **UI and Styling Adjustments**: Several UI and styling adjustments were made to improve the appearance and positioning of the fullscreen controls, such as setting the buttons' background to transparent and adjusting their size and margin.
5. **Removal of Static Image Source for Fullscreen Button**: The static image source for the fullscreen button was removed, aligning with the shift towards a font icon-based approach for controls.
6. **Event Handling Adjustments**: Minor adjustments were made to event handling, particularly in managing the visibility of the button container in response to pointer movements, ensuring intuitive user interactions.

These changes collectively enhance the `MauiMediaElement` by making the fullscreen controls more adaptable, visually consistent, and user-friendly.

 ### Linked Issues ###
 - Fixes #1862

 ### PR Checklist ###

 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###
Fixes an issue where if you create a visual studio project and add a second project to it. Adding media element to both projects and will get a file duplication error when attempting to build the project. This bug is fixed by not using a file image source and switching to using a `FontIcon`.

2024-05-09 16:29 UTC, mhrastegari requested changes

2024-05-09 16:36 UTC, mhrastegari requested changes

2024-05-09 16:36 UTC, mhrastegari commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +			Foreground = new SolidColorBrush(Colors.White),
Another suggestion I have is to not giving the button any colors to have its default colors which adapts itself with OS's dark and light mode just like Media Element transport controls

2024-05-09 17:00 UTC, ne0rrmatrix commented
@mhrastegari  Thank you for the excellent suggestions. Good catch! PR has been updated as you suggested.

2024-05-09 17:24 UTC, mhrastegari commented
Happy to help 🥰 @ne0rrmatrix

2024-05-09 22:40 UTC, briankanelson commented
I have downloaded the nuget and tested it against my project and both issues are resolved (Exiting full screen works ok, and there is no duplicate file error).

2024-05-09 22:40 UTC, briankanelson approved these changes

2024-05-09 22:48 UTC, pictos commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +        };
these can be cached and static, instead of being generated all the time

2024-05-09 23:56 UTC, ne0rrmatrix commented
@pictos I updated it as requested.

2024-05-24 17:44 UTC, bijington submitted a review, later dismissed
One minor comment on something you haven't changed but it stood out to me. Feel free to ignore if you like

2024-05-24 20:19 UTC, bijington commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +			exitFullScreenButton.Click -= OnFullScreenButtonClick;
The if statement (line 171) itself doesn't but inside both branches we change the subscription to different buttons depending on that branch.

2024-05-24 20:25 UTC, ne0rrmatrix commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +			exitFullScreenButton.Click -= OnFullScreenButtonClick;
I am happy to change it. Will get that done after I get some sleep. Can you describe how you want it handled? Or feel free to make an edit.

2024-05-24 20:43 UTC, ne0rrmatrix commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +			exitFullScreenButton.Click -= OnFullScreenButtonClick;
Updated as requested. Now the method only changes the icon and no longer removes and adds children buttons.

2024-05-24 20:49 UTC, bijington commented on src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs
> +			exitFullScreenButton.Click -= OnFullScreenButtonClick;
That was a quick sleep! Thanks, the change wasn't quite what I was thinking but I think this is more elegant.

2024-05-24 20:49 UTC, bijington approved these changes

2024-05-27 08:25 UTC, merged