Remove ViewModel depends on ContentPage
CommunityToolkit/Maui pull request #250
Opened 2022-01-18 12:48 UTC by VladislavAntonyuk

### Description of Change ###

Remove ViewModel dependency from ContentPage.

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

2022-01-18 12:50 UTC, VladislavAntonyuk commented on samples/CommunityToolkit.Maui.Sample/Pages/Base/BasePage.cs
> +	public BasePage() : this(ServiceProvider.GetRequiredService<TViewModel>())
empty ctor is required for MAUI (it will be fixed in preview 12)

2022-01-23 20:05 UTC, pictos requested changes
That looks cleaner to me, I have some comments and I found an issue on Windows (so far) I can't navigate to the sample page if I navigate back, I need to go to another sample and navigate again.

On video:
1. I navigate to `DoubleToIntConverter` 
2. Navigate back
3. clicked again on `DoubleToIntConverter`
4. Nothing happened


https://user-images.githubusercontent.com/20712372/150696067-95088523-69ac-46df-9cca-e956e73d465a.mp4

2022-01-23 20:05 UTC, pictos commented on samples/CommunityToolkit.Maui.Sample/Pages/Base/ViewModelLocator.cs
> +		mappings = new Dictionary<Type, string>();
```suggestion
	internal static readonly Dictionary<Type, string> mappings = new();

	static ViewModelLocator()
	{
```

2022-01-24 02:33 UTC, brminnick commented
Thanks Vlad! I'm concerned with how this increases the complexity of the sample app. 

We have a tough job of balancing the need to ensure that the sample app both follows best practices, and ensuring the sample app is simple enough for a community member to easily add content too.

I agree that it is a good idea to remove the `ContentPage` references from the `BaseGalleryViewModel` classes. This currently causes our app to consume a lot of memory because every of `ContentPage` is initialized in the `BaseGalleryViewModel` (and each `ContentPage`'s View Model is also instantiated).

## Alternative Implementation

👇 Here's an idea I came up with tonight that might accomplish everything we need without making the sample app too complicated.

I'll open a PR for this tonight (assuming it works) and let's chat about both options.

- **SectionModel.cs**
  - Replace `ContentPage` Parameter /Property with `Type` Parameter / Property

- **ServiceProvider.cs**
  - Add an Overload for `GetRequiredService`
  ```cs
  public static object GetRequiredService(Type type) => Current.GetRequiredService(type);
  ```
- **BaseGalleryPage.cs**
  - Update `HandleSelectionChanged`

  ```cs
  async void HandleSelectionChanged(object? sender, SelectionChangedEventArgs e)
  {
	  ArgumentNullException.ThrowIfNull(sender);
  
	  var collectionView = (CollectionView)sender;
	  collectionView.SelectedItem = null;
  
	  if (e.CurrentSelection.FirstOrDefault() is SectionModel sectionModel)
	  {
		  var page = (BasePage)ServiceProvider.GetRequiredService(sectionModel.PageType)
		  await Navigation.PushAsync(page);
	  }
  }
  ```

2022-01-24 03:27 UTC, brminnick commented
It worked! Here's the link to the PR:
https://github.com/CommunityToolkit/Maui/pull/258

This week (and maybe also in the upcoming standup) let's chat about the pros + cons of each, and we can likely combine the pros from both into the Sample App 👍

2022-02-03 04:03 UTC, brminnick commented
Hey Vlad! I tweaked a couple things in the sample app to hopefully make it easier for devs to add their new sample pages and view models :

1. Merged `LocatorService` into `AppShell.xaml.cs`
    - Since `App.xaml.cs` sets `MainPage = new AppShell()`, new devs should easily find `AppShell` and see where to add their View Model mappings and register routes
2. Refactored `SectionModel` to use Factory Pattern
    - Made `SectionModel` constructor private
    - Created `public SectionModel Create<TViewModel> where T : BaseViewModel`  
      -  Ensures that every `public Type ViewModelType` is of type `BaseViewModel`
3. Create `WelcomePage`
    - Makes a more user-friendly landing page when the sample app launches

2022-02-03 04:15 UTC, brminnick commented
And just FYI - it looks like the Flyout Shell hasn't ben fully implemented on iOS/MacCatalyst yet.

(The top navigation bar is missing)

<img width="789" alt="image" src="https://user-images.githubusercontent.com/13558917/152280077-319cdd99-fd31-49af-ac62-81004b781c26.png">

2022-02-03 21:28 UTC, VladislavAntonyuk commented on samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
> +		}
it throws rather abstract error message:
![image](https://user-images.githubusercontent.com/33021114/152431526-6d97a0d8-a199-4269-b82a-559dce6baa51.png)
I will change message a bit to return more informative message

2022-02-06 23:19 UTC, brminnick approved these changes
Hey Vlad! I just added a couple commits to simplify the Routing Registration, and I also added a work-around for the iOS Shell appearance bugs. 

If you're cool with the updates, go ahead and merge this PR! 🙌 

@pictos I confirmed that the Windows App bug you pointed out is currently happening on the `main` branch. I haven't dug into it, but I think you're right that it is a `CollectionView` bug. Since it's not related to this PR/Shell, I think we're good to move forward with this PR 👍

2022-02-07 04:43 UTC, VladislavAntonyuk commented
Thank you @brminnick!

2022-02-07 04:46 UTC, merged