Refactor the IntToBoolConverter to use the BaseConverter
CommunityToolkit/Maui pull request #327
Opened 2022-03-16 14:16 UTC by bijington

### Description of Change ###

 

Refactors the `IntToBoolConverter` to use the `BaseConverter`.

 ### Linked Issues ###
 

n/a

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

2022-03-16 16:37 UTC, brminnick requested changes

2022-03-16 16:37 UTC, brminnick commented on src/CommunityToolkit.Maui/Converters/IntToBoolConverter.shared.cs
> +	public abstract int ConvertBackTo(bool value) => value ? 1 : 0;
I assume `abstract` is a typo since it's also implemented?

2022-03-16 22:27 UTC, brminnick commented
Adding the `blocked` tag until https://github.com/CommunityToolkit/Maui/pull/325 is merged

2022-03-16 22:51 UTC, brminnick requested changes
Thanks Shaun!

Could you also fix the Test Method names?
- `IndexToArrayConverter` -> `IntToBoolConverter`
- `IndexToArrayConverterBack` -> `IntToBoolConverterBack`

2022-03-16 22:51 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Converters/IntToBoolConverter_Tests.cs
> +		Assert.Equal(typedResult, expectedResult);
Let's swap these `Assert.Equal` parameters around.

It's kinda trivial, but when the `Assert` fails, it'll print "...Expected: [first parameter] Actual: [second parameter]" which can be confusing if the parameters are reversed

```suggestion
		Assert.Equal(expectedResult, result);
		Assert.Equal(expectedResult, typedResult);
```

2022-03-16 22:51 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Converters/IntToBoolConverter_Tests.cs
> +		Assert.Equal(typedResult, expectedResult);
Let's swap these `Assert.Equal` parameters around.

It's kinda trivial, but when the `Assert` fails, it'll print "...Expected: [first parameter] Actual: [second parameter]" which can be confusing if the parameters are reversed.

```suggestion
		Assert.Equal(expectedResult, result);
		Assert.Equal(expectedResult, typedResult);
```

2022-03-16 22:51 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Converters/IntToBoolConverter_Tests.cs
> +	public void InValidConverterValuesThrowArgumentException(object value)
Let's fix this small typo from a previous PR

```suggestion
	public void InvalidConverterValuesThrowArgumentException(object value)
```

2022-03-16 22:51 UTC, brminnick commented on src/CommunityToolkit.Maui.UnitTests/Converters/IntToBoolConverter_Tests.cs
> +	public void InValidConverterBackValuesThrowArgumentException(object value)
Let's fix this small typo from a previous PR
```suggestion
	public void InvalidConverterBackValuesThrowArgumentException(object value)
```

2022-03-20 19:30 UTC, brminnick approved these changes

2022-03-20 19:30 UTC, bijington commented
@brminnick rhanks for the fix. I haven't removed the extensions around asserting the Excoetional conditions. What are your thoughts?

2022-03-20 19:35 UTC, brminnick submitted a review, later dismissed

2022-03-20 19:36 UTC, brminnick commented
Hey Shaun! I went ahead and pulled out the converter assert extension methods. I think it's best to keep the Unit Tests as simple/dumb as possible to make it easier for us to understand why unit tests are failing when writing future PRs.

For example, when Vincent Hoogendoorn wrote the unit tests for the Markup library, he made them very complex and now it's tough to understand what a Unit Test is doing and, worse, to understand why a Unit Test is failing: https://github.com/CommunityToolkit/Maui.Markup/blob/main/src/CommunityToolkit.Maui.Markup.UnitTests/BindableObjectExtensionsTests.cs

2022-03-20 19:38 UTC, bijington commented
No problem, I get that argument and missed you had removed them. I wanted to make sure before this went in 😃

2022-03-20 19:42 UTC, brminnick approved these changes

2022-03-20 20:02 UTC, merged