Port BadgeView from XCT
CommunityToolkit/Maui pull request #345
Opened 2022-03-30 21:21 UTC by tnassour

### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

2022-03-30 21:51 UTC, brminnick commented
Assigning [Proposal](https://github.com/CommunityToolkit/Maui/issues/105) Champion, @pictos

2022-03-31 07:05 UTC, VladislavAntonyuk requested changes

2022-03-31 07:05 UTC, VladislavAntonyuk commented on samples/CommunityToolkit.Maui.Sample/ViewModels/Views/BadgeViewViewModel.cs
> +	public ICommand IncreaseCommand { get; }
Use ICommand attribute instead

2022-03-31 07:05 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/Views/BadgeView/BadgeView.shared.cs
> +		if (BadgeText == null)
is null

2022-03-31 07:05 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/Views/BadgeView/IBadgeAnimation.shared.cs
> +public interface IBadgeAnimation
It should be in Core

2022-04-02 23:45 UTC, brminnick commented
Thanks @tnassour! 

I just wanted to give you a heads up that we'll need you to open a PR for our [Docs repo](https://github.com/MicrosoftDocs/CommunityToolkit) before we can merge this PR: https://github.com/MicrosoftDocs/CommunityToolkit

For now, I've added the `pending documentation` and `do not merge` labels so that we don't forget 👍

2022-04-10 17:15 UTC, tnassour commented on samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
> +    <MauiXaml Update="Pages\Views\BadgeViewPage.xaml">
Removed

2022-04-10 17:16 UTC, tnassour commented on samples/CommunityToolkit.Maui.Sample/Pages/Views/BadgeViewPage.xaml
> +            <StackLayout
Changed

2022-04-10 17:24 UTC, tnassour commented on samples/CommunityToolkit.Maui.Sample/ViewModels/Views/BadgeViewViewModel.cs
> +	public int Counter
modified

2022-05-09 11:29 UTC, bijington commented
@tnassour is this PR something that you are still able to look at? We are on a feature freeze until .NET MAUI GAs later this month but I would like to see this go into the next version. If you are unable it's no problem, I would be happy to assist in getting it completed.

2022-05-09 12:00 UTC, VladislavAntonyuk requested changes

2022-05-09 12:00 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/Views/BaseTemplatedView.shared.cs
> +		if (Control == null && child is TControl control)
```suggestion
		if (Control is null && child is TControl control)
```

2022-05-14 13:04 UTC, tnassour commented on src/CommunityToolkit.Maui/Views/BadgeView/IBadgeAnimation.shared.cs
> +public interface IBadgeAnimation
moved

2022-05-14 13:05 UTC, tnassour commented on src/CommunityToolkit.Maui/Views/BadgeView/BadgeView.shared.cs
> +public class BadgeView : BaseTemplatedView<Grid>
done

2022-05-14 13:05 UTC, tnassour commented on src/CommunityToolkit.Maui/Views/BadgeView/BadgeView.shared.cs
> +		if (BadgeText == null)
changed

2022-05-14 13:50 UTC, tnassour commented on src/CommunityToolkit.Maui/Views/BadgeView/BadgeView.shared.cs
> +	public string FontFamily
nope cause the label uses both FontFamily, FontAttributes and the Font property is only a getter

2022-05-14 14:02 UTC, tnassour commented on samples/CommunityToolkit.Maui.Sample/ViewModels/Views/BadgeViewViewModel.cs
> +	public ICommand IncreaseCommand { get; }
done

2022-05-14 14:15 UTC, tnassour commented
> @tnassour is this PR something that you are still able to look at? We are on a feature freeze until .NET MAUI GAs later this month but I would like to see this go into the next version. If you are unable it's no problem, I would be happy to assist in getting it completed.

@bijington i have done the modifications, it remains testing the sample solution for all of this.
While building locally i am getting this error : 
`3>CSC : error CS0016: Could not write to output file 'C:\Apps\CommunityToolKit\Maui-fork\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo_9e00a6b2-8703-4c7f-aaa2-32f7268ecea1.g.shared.cs' -- 'Could not find a part of the path 'C:\Apps\CommunityToolKit\Maui-fork\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo_9e00a6b2-8703-4c7f-aaa2-32f7268ecea1.g.shared.cs'.'`

can someone tell me how to fix this ?

2022-05-14 14:45 UTC, VladislavAntonyuk commented
> > @tnassour is this PR something that you are still able to look at? We are on a feature freeze until .NET MAUI GAs later this month but I would like to see this go into the next version. If you are unable it's no problem, I would be happy to assist in getting it completed.
> 
> @bijington i have done the modifications, it remains testing the sample solution for all of this. While building locally i am getting this error : `3>CSC : error CS0016: Could not write to output file 'C:\Apps\CommunityToolKit\Maui-fork\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo_9e00a6b2-8703-4c7f-aaa2-32f7268ecea1.g.shared.cs' -- 'Could not find a part of the path 'C:\Apps\CommunityToolKit\Maui-fork\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo_9e00a6b2-8703-4c7f-aaa2-32f7268ecea1.g.shared.cs'.'`
> 
> can someone tell me how to fix this ?

https://github.com/CommunityToolkit/Maui/issues/340#issuecomment-1081052363

2022-06-30 06:32 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/Views/BaseTemplatedView.shared.cs
> +public abstract class BaseTemplatedView<TControl> : TemplatedView where TControl : View, new()
TemplatedView uses Compatibility StackLayout. I think we shouldn't use controls from Compatibility namespace

2022-09-05 15:20 UTC, brminnick commented
Closing PR as stale + abandoned

2022-09-05 15:20 UTC, closed without merging