DrawingView DisconnectHandler
CommunityToolkit/Maui pull request #420
Opened 2022-05-21 17:32 UTC by VladislavAntonyuk

### Description of Change ###

https://github.com/dotnet/maui/issues/3604

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

2022-05-21 18:41 UTC, brminnick requested changes
Thanks Vlad! Looks good 👍 

The change requested is just a cosmetic request to keep the private methods together in the file.

2022-05-21 18:41 UTC, brminnick commented on src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
> +	}
Thanks Vlad! Let's move this method down next to the other private methods in the file.

2022-05-21 19:06 UTC, pictos commented on src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
> +	void DrawingView_Unloaded(object? sender, EventArgs e)
just a name change
```suggestion
	void OnDrawingViewUnloaded(object? sender, EventArgs e)
```

2022-05-21 19:07 UTC, pictos commented on src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
> +		Unloaded += DrawingView_Unloaded;
```suggestion
		Unloaded += OnDrawingViewUnloaded;
```

2022-05-21 19:07 UTC, pictos commented on src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
> +		Unloaded -= DrawingView_Unloaded;
```suggestion
		Unloaded -= OnDrawingViewUnloaded;
```

2022-05-21 21:08 UTC, pictos approved these changes
LGTM!

2022-05-24 01:07 UTC, brminnick approved these changes

2022-05-24 01:07 UTC, merged