Added warning about the usage of the custom schema
CommunityToolkit/Maui pull request #429
Opened 2022-05-28 00:10 UTC by pictos

### Description of Change ###

Added more info about the usage of the custom schema xmlns.

 ### Linked Issues ###
 

 - Related to #427

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

2022-05-28 16:50 UTC, bijington commented
Thanks @pictos I really like the idea! I would like us to provide some information around the differences between using a library and app project and give an example of how to overcome it, perhaps this should go in the NuGet read me file too.

I'm hoping to watch that video on the subject so I have a better understanding before I make some full suggestions though.

2022-05-28 18:19 UTC, VladislavAntonyuk commented on src/CommunityToolkit.Maui/ReadMe.txt
> +In order to use the custom schema mentioned above you need to call the `UseMauiCommunityToolkit` method or call any API on C# code. If you don't do that that url will not work and you need to use the
could we also add it to this page as well: https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started

2022-05-28 18:19 UTC, VladislavAntonyuk approved these changes

2022-05-28 18:23 UTC, brminnick requested changes
I prefer that we fix the problem by adding a Source Generator  instead of adding a warning to the docs that (let's be honest) most developers won't read

2022-05-28 20:13 UTC, pictos commented
@brminnick how do you feel about merging this and creating an issue to use an SG to fix the issue?
If you go on our discord channel, you'll see some points that we need to test and make sure that SG will work as expected.

2022-05-28 20:14 UTC, bijington commented
> @brminnick how do you feel about merging this and creating an issue to use an SG to fix the issue?
> If you go on our discord channel, you'll see some points that we need to test and make sure that SG will work as expected.

If we do merge I would like to reword it a bit to make it a little bit more helpful in guiding developers on how to workaround the issue.

2022-05-28 20:55 UTC, pictos commented
@bijington do you have something in mind already? If so feel free to push the changes to this PR

2022-05-28 20:56 UTC, bijington commented
> @bijington do you have something in mind already? If so feel free to push the changes to this PR

Yeah I can happily provide something on this

2022-06-09 19:25 UTC, bijington commented
Sorry I should add my content to this! I'll try and do that this weekend

2022-07-14 22:11 UTC, brminnick commented
`.UseMauiCommunityToolkit()` Analyzer added in #486

2022-07-14 22:23 UTC, pictos commented
@brminnick should we close this? Or still is good to have this in some "docs"?

2022-07-14 22:35 UTC, brminnick commented
I'd like to add implement two more things to the code base before we close this:
1. A `CommunityToolkit.Maui.Init()` method that a user can call from a class library 
  - This provides a work-around for devs using the .NET MAUI Community Toolkit in a class library to
  - The method wouldn't actually do anything (eg it wouldn't wire-up handlers), but it ensures that they have written C# code from `CommunityToolkit.Maui` and the custom schema will not fail
2. An analyzer that verifies a developer as called `CommunityToolkit.Maui.Init()` in their class library

  ```cs
  public static void Init()
  {
    
  }
  ```

Having this PR open is a good reminder that we still need to do it!

2023-01-09 03:36 UTC, brminnick commented
Superseded by https://github.com/CommunityToolkit/Maui/pull/486

2023-01-09 03:36 UTC, closed without merging