Add MediaElement.Aspect Functionality
CommunityToolkit/Maui pull request #918
Opened 2023-01-22 16:49 UTC by jfversluis

Adds the aspect functionality for MediaElement

2023-01-22 19:37 UTC, VladislavAntonyuk approved these changes

2023-01-23 01:46 UTC, pictos requested changes
Just a small design detail

2023-01-23 01:46 UTC, pictos commented on src/CommunityToolkit.Maui.MediaElement/Interfaces/IMediaElement.cs
> +	Aspect Aspect { get; set; }
If the Platform layer will not `set` the aspect, it should be readonly, from what I saw in the code... The platform layer just reads this value and applies it. If I missed something, please let me know

```suggestion
	Aspect Aspect { get; }
```

2023-01-23 14:40 UTC, pictos approved these changes
Looks great!

2023-01-23 14:52 UTC, merged